apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-npr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-npr
  template:
    metadata:
      labels:
        app: my-app-npr
    spec:
      containers:
      - name: my-containerr
        image: sreekanth143/java-web-app-docker:app1
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-npr
  labels:
    app: my-app-npr
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: my-app-npr

